hoist: false
hoistPattern: []
minimumReleaseAge: 0 # FIXME: Get rid of this
autoInstallPeers: false
strictPeerDependencies: true
publicHoistPattern:
  - "frida"
  - "vitest"
  - "@types/*"
  - "@vitest/*"
  - "@effect/vitest"

recursiveInstall: true
dedupePeerDependents: false
linkWorkspacePackages: true
hoistWorkspacePackages: false
preferWorkspacePackages: true
resolvePeersFromWorkspaceRoot: false

packages:
  - packages/*
  - scratchpad
  - templates/agent-only
  - templates/app-and-agent

allowBuilds:
  frida: true
  esbuild: true
  msgpackr-extract: true
  '@bufbuild/buf': true

overrides:
  "@effect/docgen>typescript": "6.0.3"
  "madge>typescript": "6.0.3"

peerDependencyRules:
  allowedVersions:
    typescript: "6.0.3"
