remote_theme: mikearnaldi/just-the-docs

baseurl: "/efffrida"
repository: "leonitousconforti/efffrida"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
"efffrida on GitHub":
  - "https://github.com/leonitousconforti/efffrida"
